name: iwd23
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  http: ^0.13.5
  provider: ^6.0.5

  flutter_screenutil: ^5.7.0
  flutter_secure_storage: ^8.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  easy_localization:
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  awesome_snackbar_content: ^0.1.1
  lottie: ^2.3.0
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.8.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - images/

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 400
  
  
  
  
  
  
